---
title: "Untitled"
output: pdf_document
date: "2023-05-02"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)

#importing 20 years of NBA Draft dataset
NBA_data <- read_csv("C:\\Users\\Admin\\Documents\\Springsem_courses\\stat231\\1-singhania-sriyash\\data\\draft-data-20-years.csv")
NBA_abb <- read_csv("C:\\Users\\Admin\\Documents\\Springsem_courses\\stat231\\1-singhania-sriyash\\data\\NBA_abb.csv")
NBA_states <- read_csv("C:\\Users\\Admin\\Documents\\Springsem_courses\\stat231\\1-singhania-sriyash\\data\\NBA_states.csv")

filtered_data <- NBA_data %>%
  rename_at('Tm', ~'Franchise')%>%
  filter(!(DraftYear %in% c(1990, 1991, 1992, 1993, 1994, 1995, 1996, 1997, 1998, 1999)))%>%
  select(-c(playerurl, DraftYr, MPG, PPG, RPG, APG, VORP, BPM, "WS/48"))%>%
  filter(!(College %in% c(NA)))%>%
  arrange(tolower(Franchise))

team_names <- inner_join(filtered_data, NBA_abb, by=c("Franchise" = "Abbreviation/"))%>%
  rename_at('Franchise.y', ~'NBA Team(s)')

teamstates <- inner_join(team_names, NBA_states, by=c("NBA Team(s)" = "NBA Team(s)"))

states_map <- maps::map("state", regions = "."
                        , plot = FALSE, fill = TRUE) %>%
  sf::st_as_sf()

state_info <- data.frame(state_full = tolower(state.name)
                         , 'State Name' = state.abb)

avgData <- teamstates %>% 
  drop_na() %>%
  mutate(avgRaw = TOTPTS/G) %>%
  rename(state = 'State Name') %>%
  group_by(state) %>%
  summarise(finalMean = mean(avgRaw))%>%
  rename(ID = state) %>%
  mutate(ID = tolower(ID)) %>%
  right_join(states_map, by = "ID") 

ggplot(avgData, aes(geometry=geom, fill = finalMean)) +
  geom_sf() +
  theme_void() +
  labs(fill = "Average Points(per game)"
       , title = "Average Points Scored by NBA Players in U.S States."
       , caption = "Source: NBA Dataset on Kaggle") +
  scale_fill_viridis_c(option = "magma", direction = -1)

second_plot <- teamstates %>%
  drop_na() %>%
  mutate(valuepick = WS/G)%>%
  rename(statedata = 'State Name')%>%
  group_by(statedata)%>%
  summarise(finalMeanValuePick = mean(valuepick))%>%
  rename(ID = statedata) %>%
  mutate(ID = tolower(ID)) %>%
  right_join(states_map, by = "ID")

ggplot(second_plot, aes(geometry=geom, fill = finalMeanValuePick)) +
  geom_sf() +
  theme_void() +
  labs(fill = "Mean Value Pick"
       , title = "Average Mean Value of NBA Players in U.S States."
       , caption = "Source: NBA Dataset on Kaggle") +
  scale_fill_viridis_c(option = "blues", direction = -1)

```